name: Android CI - Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # ✅ Télécharger et configurer Gradle 8.7 manuellement
      - name: Install Gradle 8.7
        run: |
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-8.7-bin.zip -d $HOME
          echo "$HOME/gradle-8.7/bin" >> $GITHUB_PATH
          gradle -v

      # 🏗 Construire l'APK Debug en utilisant le Gradle qu'on vient d'installer
      - name: Build Debug APK
        run: |
          gradle --version
          gradle assembleDebug

      # 📦 Uploader l'APK généré
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Scan-elec-debug-apk
          path: app/build/outputs/apk/debug/*.apk
