name: Android CI - Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # ✅ Installer Gradle 8.7 manuellement (apt est trop ancien)
      - name: Install Gradle 8.7
        run: |
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip gradle-8.7-bin.zip -d /usr/local/
          ln -s /usr/local/gradle-8.7 /usr/local/gradle
          echo "export PATH=/usr/local/gradle/bin:$PATH" >> $GITHUB_ENV
          gradle -v

      # 🏗 Construire l'APK Debug
      - name: Build Debug APK
        run: gradle assembleDebug

      # 📦 Uploader l'APK généré en artifact téléchargeable
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Scan-elec-debug-apk
          path: app/build/outputs/apk/debug/*.apk
